<?php

class ImportConfig
{
	private $configs;

	public function __construct()
	{
		$this->configs[56631] = 
		[
			'model_replace' => 
			[
				'HKPL' => 'Hakkapeliitta',
				'IC-7' => 'Ice Cruiser 7',
				'IG-35' => 'IG35',
				'CARGO SPEED' => 'CARGOSPEED',
				'С' => 'C',
				'OBGSi5'  => 'Observe GSi-5',
				'PXT1R'  => 'Proxes T1-R',
			],
			'brand_model_replace_all' =>
			[
				'NORDMAN NORDMAN SZ' => 'NOKIAN TYRES NORDMAN SX',
				'MICHELIN LATITUDE X-ICE NORTH 2+' => 'MICHELIN LATITUDE X-ICE NORTH 2 +',
				'TRIANGLE TR652' => 'TRIANGLE GROUP TR652',
				'TRIANGLE TR928' => 'TRIANGLE GROUP TR928',
				'NOKIAN HAKKAPELIITTA R' => 'NOKIAN TYRES HAKKAPELIITTA R',
				'NOKIAN WR A3' => 'NOKIAN TYRES WR A3',
				'MICHELIN LATITUDE X-ICE NORTH 2' => 'MICHELIN LATITUDE X-ICE NORTH 2 +',
				'NORDMAN NORDMAN 5' => 'NOKIAN TYRES NORDMAN 5 SUV',
				'PIRELLI SCORPION VERDE ALL-SEASON' => 'PIRELLI SCORPION VERDE ALL SEASON',
				'MAXXIS HP-M3 BRAVO' => 'MAXXIS BRAVO HP-M3',
				'CONTINENTAL CONTIPREMIUMCONTACT-5' => 'CONTINENTAL CONTIPREMIUMCONTACT 5',
				'NORDMAN NORDMAN S SUV' => 'NOKIAN TYRES NORDMAN S SUV',
				'NOKIAN HAKKA BLUE SUV' => 'NOKIAN TYRES HAKKA BLUE SUV',
				'BRIDGESTONE SPORTY STYLE MY-02' => 'BRIDGESTONE MY-02 SPORTY STYLE',
				'NOKIAN HAKKA C2' => 'NOKIAN TYRES HAKKA C2',
				'HANKOOK OPTIMO ME02 K424' => 'HANKOOK TIRE K424 (OPTIMO ME02)',
				'NOKIAN HAKKAPELIITTA 9' => 'NOKIAN TYRES HAKKAPELIITTA 9',
				'NORDMAN NORDMAN 7 SUV' => 'NOKIAN TYRES NORDMAN 7 SUV',
				'MARSHAL MATRAC FX MU11.' => 'MARSHAL MATRAC FX MU11',
				'HANKOOK OPTIMO K715' => 'HANKOOK TIRE OPTIMO K715',
				'HANKOOK VENTUS S1 EVO 2 K117A SUV' => 'HANKOOK TIRE VENTUS S1 EVO 2 SUV K117A',
				'CORDIANT CORDIANT BUSINESS CW-2' => 'CORDIANT BUSINESS CW 2',
				'TIGAR WINTER' => 'TIGAR WINTER 1',
				'CORDIANT CORDIANT POLAR 2' => 'CORDIANT POLAR 2',
				'MAXXIS MCV3+ VANSMART' => 'MAXXIS VANSMART MCV3+',
				'NOKIAN HAKKA BLUE 2 SUV' => 'NOKIAN TYRES HAKKA BLUE 2 SUV',
				'TRIANGLE TR292' => 'TRIANGLE GROUP TR292',
				'NORDMAN NORDMAN SX2' => 'NOKIAN TYRES NORDMAN SX2',
				'CONTINENTAL VANCO-2' => 'CONTINENTAL VANCO 2',
				'NOKIAN HAKKAPELIITTA 8 SUV' => 'NOKIAN TYRES HAKKAPELIITTA 8 SUV',
				'HANKOOK VENTUS ST RH06' => 'HANKOOK TIRE VENTUS ST RH06',
				'CONTINENTAL PREMIUMCONTACT-6' => 'CONTINENTAL PREMIUMCONTACT 6',
				'NOKIAN WR D4' => 'NOKIAN TYRES WR D4',
				'NOKIAN WR SUV 3' => 'NOKIAN TYRES WR SUV 3',
				'TRIANGLE TE301' => 'TRIANGLE GROUP TE301',
				'VIATTI VIATTI BRINA NORDICO V-522' => 'VIATTI BRINA NORDICO V-522',
				'VIATTI VIATTI BOSCO NORDICO V-523' => 'VIATTI BOSCO NORDICO V-523',
				'VIATTI VIATTI VETTORE BRINA V-525' => 'VIATTI VETTORE BRINA V-525',
				'MAXXIS AT-771 BRAVO' => 'MAXXIS BRAVO AT-771',
				'NOKIAN HAKKAPELIITTA C3' => 'NOKIAN TYRES HAKKAPELIITTA C3',
				'NOKIAN HAKKAPELIITTA R2' => 'NOKIAN TYRES HAKKAPELIITTA R2',
				'КАМА EURO КАМА EURO-131' => 'КАМА-ЕВРО KАМА-EURO LCV-131',
				'BRIDGESTONE BLIZZAK REVO-GZ' => 'BRIDGESTONE BLIZZAK REVO GZ',
				'NORDMAN NORDMAN C' => 'NOKIAN TYRES NORDMAN C',
				'YOKOHAMA IG50' => 'YOKOHAMA ICE GUARD IG50',
				'GOODYEAR EAGUGGW3' => 'GOODYEAR EAGLE UG GW-3',
				'NEXEN WG-WINSPIKE WH62' => 'NEXEN WINGUARD WINSPIKE WH62',
				'TRIANGLE TR258' => 'TRIANGLE GROUP TR258',
				'TRIANGLE TR257' => 'TRIANGLE GROUP TR257',
				'AMTEL PLANET AMTEL PLANET 2P' => 'AMTEL PLANET 2P',
				'TRIANGLE TR609' => 'TRIANGLE GROUP TR609',
				'MICHELIN ALPIN-A4' => 'MICHELIN ALPIN A4',
				'HANKOOK DYNAPRO MT RT03' => 'HANKOOK TIRE DYNAPRO MT RT03',
				'HANKOOK DYNAPRO HP RA23' => 'HANKOOK TIRE DYNAPRO HP RA23',
				'TRIANGLE TR787' => 'TRIANGLE GROUP TR787',
				'TRIANGLE TR777' => 'TRIANGLE GROUP TR777',
				'TRIANGLE TR968' => 'TRIANGLE GROUP TR968',
				'NORDMAN NORDMAN RS2' => 'NOKIAN TYRES NORDMAN RS2',
				'FORMULA FORMULA ICE' => 'FORMULA ICE',
				'CONTINENTAL CONTISPORTCONTACT-2' => 'CONTINENTAL CONTISPORTCONTACT 2',
				'TRIANGLE TR646' => 'TRIANGLE GROUP TR646',
				'NOKIAN HAKKA GREEN 2' => 'NOKIAN TYRES HAKKA GREEN 2',
				'NOKIAN ROTIIVA A/T PLUS' => 'NOKIAN TYRES ROTIIVA A/T PLUS',
				'CONTINENTAL CONTIVIKINGCONTACT-6' => 'CONTINENTAL CONTIVIKINGCONTACT 6',
				'CORDIANT CORDIANT POLAR SL' => 'CORDIANT POLAR SL',
				'VIATTI VIATTI BOSCO S/T V-526' => 'VIATTI BOSCO S/T V-526',
				'NOKIAN WR A4' => 'NOKIAN TYRES WR A4',
				'NOKIAN HAKKA BLACK SUV' => 'NOKIAN TYRES HAKKA BLACK SUV',
				'NOKIAN HAKKA BLACK 2' => 'NOKIAN TYRES HAKKA BLACK 2',
				'MARSHAL WINTERCRAFT SUV ICE WS31.' => 'MARSHAL WINTERCRAFT SUV ICE WS31',
				'MARSHAL POWER GRIP KC11.' => 'MARSHAL POWER GRIP KC11',
				'MARSHAL WINTER PORTRAN CW51.' => 'MARSHAL WINTER PORTRAN CW51',
				'KORMORAN SNOWPRO B2.' => 'KORMORAN SNOWPRO B2',
				'KORMORAN VANPRO WINTER.' => 'KORMORAN VANPRO WINTER',
				'TRIANGLE TR978' => 'TRIANGLE GROUP TR978',
				'HANKOOK KINERGY ECO K425' => 'HANKOOK TIRE KINERGY ECO K425',
				'NOKIAN HAKKAPELIITTA R3 SUV' => 'NOKIAN TYRES HAKKAPELIITTA R3 SUV',
				'NOKIAN HAKKAPELIITTA R3' => 'NOKIAN TYRES HAKKAPELIITTA R3',
				'TRIANGLE TR259' => 'TRIANGLE GROUP TR259',
				'BLACKLION W517 WINTER TAMER' => 'BLACKLION WINTER TAMER W517',
				'KORMORAN SUV SUMMER.' => 'KORMORAN SUV SUMMER',
				'NOKIAN HAKKA BLUE 2' => 'NOKIAN TYRES HAKKA BLUE 2',
				'TRIANGLE TR246' => 'TRIANGLE GROUP TR246',
				'MAXXIS HP5 PREMITRA' => 'MAXXIS PREMITRA HP5',
				'TRIANGLE TR248' => 'TRIANGLE GROUP TR248',
				'KORMORAN GAMMA B2.' => 'KORMORAN GAMMA B2',
				'HANKOOK DYNAPRO HP2 RA33' => 'HANKOOK TIRE DYNAPRO HP2 RA33',
				'NOKIAN ROCKPROOF' => 'NOKIAN TYRES ROCKPROOF',
				'HANKOOK VENTUS ME01 K114' => 'HANKOOK TIRE VENTUS ME01 K114',
				'HANKOOK VENTUS S1 EVO 2 K117' => 'HANKOOK TIRE VENTUS S1 EVO 2 K117',
				'HANKOOK VENTUS R-S3 Z222' => 'HANKOOK TIRE VENTUS R-S3 Z222',
				'KORMORAN IMPULSER B4.' => 'KORMORAN IMPULSER B4',
				'NOKIAN HAKKAPELIITTA CR3' => 'NOKIAN TYRES HAKKAPELIITTA CR3',
				'VIATTI VIATTI VETTORE INVERNO V-524' => 'VIATTI VETTORE INVERNO V-524',
				'NOKIAN HAKKA BLUE' => 'NOKIAN TYRES HAKKA BLUE',
				'NOKIAN WR C3' => 'NOKIAN TYRES WR C3',
				'NORDMAN NORDMAN RS2 SUV' => 'NOKIAN TYRES NORDMAN RS2 SUV',
				'MAXXIS VS-01 VICTRA SPORT' => 'MAXXIS VICTRA SPORT VS-01',
				'CONTINENTAL CONTISPORTCONTACT-5P' => 'CONTINENTAL CONTISPORTCONTACT 5P',
				'VIATTI VIATTI BRINA V-521' => 'VIATTI BRINA V-521',
				'NOKIAN HAKKA BLACK' => 'NOKIAN TYRES HAKKA BLACK',
				'CONTINENTAL CONTISPORTCONTACT-3' => 'CONTINENTAL CONTISPORTCONTACT 3',
				'PIRELLI WINTER CHRONO' => 'PIRELLI CHRONO WINTER',
				'PIRELLI SCORPION ICE & SNOW' => 'PIRELLI SCORPION ICE&SNOW',
				'CONTINENTAL CONTISPORTCONTACT-5' => 'CONTINENTAL CONTISPORTCONTACT 5',
				'NOKIAN HAKKAPELIITTA R2 SUV' => 'NOKIAN TYRES HAKKAPELIITTA R2 SUV',
				'NOKIAN HAKKAPELIITTA 8' => 'NOKIAN TYRES HAKKAPELIITTA 8',
				'FORMULA FORMULA ENERGY' => 'FORMULA ENERGY',
				'КАМА FLAME' => 'КАМА КАМА-FLAME',
				'TRIANGLE TR918' => 'TRIANGLE GROUP TR918',
				'HANKOOK I*PIKE RW11' => 'HANKOOK TIRE I*PIKE RW11',
				'HANKOOK DYNAPRO I*CEPT RW08' => 'HANKOOK TIRE DYNAPRO I*CEPT RW08',
				'HANKOOK WINTER I*PIKE RS W419' => 'HANKOOK TIRE WINTER I*PIKE RS W419',
				'HANKOOK WINTER I*CEPT RS2 W452' => 'HANKOOK TIRE WINTER I*CEPT RS2 W452',
				'HANKOOK WINTER I*PIKE RS2 W429' => 'HANKOOK TIRE WINTER I*PIKE RS2 W429',
				'HANKOOK WINTER I*CEPT RS W442' => 'HANKOOK TIRE WINTER I*CEPT RS W442',
				'CONTINENTAL TS850' => 'CONTINENTAL CONTIWINTERCONTACT TS850',
				'YOKOHAMA IG55' => 'YOKOHAMA ICE GUARD IG55',
				'BFGOODRICH MUD TERRAIN KM2' => 'BFGOODRICH MUD-TERRAIN T/A KM2',
				'KUMHO WP51' => 'KUMHO WINTERCRAFT WP51',
				'KUMHO CW51' => 'KUMHO WINTER PORTRAN CW51',
				'KUMHO KC15' => 'KUMHO I\'ZEN KC15',
				'KUMHO KW21' => 'KUMHO ICE POWER KW21',
				'KUMHO KR26' => 'KUMHO SENSE KR26',
				'MAXXIS UE168' => 'MAXXIS UE168 (N)',
				'MAXXIS SP02' => 'MAXXIS SP02 ARCTIC TREKKER',
				'KUMHO KC11' => 'KUMHO POWER GRIP KC11',
				'KUMHO KU31' => 'KUMHO ECSTA SPT KU31',
				'YOKOHAMA V105S' => 'YOKOHAMA ADVAN SPORT V105',
				'BLACKLION BL4S 4SEASONS' => 'BLACKLION BL4S 4SEASONS ECO',
				'YOKOHAMA V905' => 'YOKOHAMA W.DRIVE V905',
				'YOKOHAMA WY01' => 'YOKOHAMA W.DRIVE WY01',
				'YOKOHAMA G075' => 'YOKOHAMA ICEGUARD SUV G075',
				'YOKOHAMA G015' => 'YOKOHAMA GEOLANDAR A/T G015',
				'BFGOODRICH ALL TERRAIN KO2' => 'BFGOODRICH ALL-TERRAIN T/A KO2',
				'KUMHO KW27' => 'KUMHO I\'ZEN KW27',
				'KUMHO KL17' => 'KUMHO ECSTA X3 KL17',
				'KUMHO PS71' => 'KUMHO ECSTA PS71',
				'KUMHO PS31' => 'KUMHO ECSTA PS31',
				'KUMHO KC53' => 'KUMHO PORTRAN KC53',
				'TRIANGLE TH201' => 'TRIANGLE GROUP SPORTEX TSH11 / SPORTS TH201',
				'KUMHO WS31' => 'KUMHO WINTERCRAFT SUV ICE WS31',
				'KUMHO PS91' => 'KUMHO ECSTA PS91',
				'YOKOHAMA V105' => 'YOKOHAMA ADVAN SPORT V105',
				'KUMHO KU36' => 'KUMHO ECSTA XS KU36',
				'NEXEN ROADIAN HT' => 'NEXEN ROADIAN H/T (LTV)',
				'KUMHO KU39' => 'KUMHO ECSTA LE SPORT KU39',
				'KUMHO WI31' => 'KUMHO WINTERCRAFT ICE WI31',
				'KUMHO KW31' => 'KUMHO I\'ZEN KW31',
				'KUMHO KH27' => 'KUMHO ECOWING ES01 KH27',
				'YOKOHAMA V103S' => 'YOKOHAMA ADVAN SPORT V103',
				'YOKOHAMA G073' => 'YOKOHAMA GEOLANDAR I/T-S G073',
				'YOKOHAMA V802' => 'YOKOHAMA ADVAN ST V802',
				'KUMHO KL51' => 'KUMHO ROADVENTURE APT KL51',
				'KUMHO KL12' => 'KUMHO ECSTA STX KL12',
				'YOKOHAMA AE01' => 'YOKOHAMA BLU EARTH AE01',
				'KUMHO HS51' => 'KUMHO ECSTA HS51',
				'KUMHO KL61' => 'KUMHO ROAD VENTURE SAT KL61',
				'KUMHO 857' => 'KUMHO RADIAL 857',
				'KUMHO KC16' => 'KUMHO I\'ZEN RV KC16',
				'YOKOHAMA G055' => 'YOKOHAMA GEOLANDAR SUV G055',
				'MAXXIS MA-S2 MARAUDER' => 'MAXXIS MA-S2 MARAUDER II',
				'MAXXIS UE103' => 'MAXXIS UE-103',
				'КАМА EURO НК-129 КАМА-EURO' => 'КАМА-ЕВРО КАМА-ЕВРО-129',
				'PIRELLI WINTER ICE ZERO FRICTION' => 'PIRELLI ICE ZERO FR',
				'CONTINENTAL TS850 P SUV' => 'CONTINENTAL CONTIWINTERCONTACT TS 850P SUV',
				'MATADOR MP92 SIBIR SNOW SUV' => 'MATADOR MP 92 SIBIR SNOW SUV M+S',
				'CONTINENTAL TS830' => 'CONTINENTAL CONTIWINTERCONTACT TS 830',
				'CONTINENTAL TS830 P' => 'CONTINENTAL CONTIWINTERCONTACT TS 830 P',	
				'DUNLOP GRASPIC DS-3' => 'DUNLOP GRASPIC DS3',
				'BRIDGESTONE DUELER A/T 697' => 'BRIDGESTONE DUELER A/T D697',
				'MATADOR MP46 HECTORRA 2' => 'MATADOR MP 46 HECTORRA 2',
				'MATADOR MP44 ELITE 3' => 'MATADOR MP 44 ELITE 3',
				'MATADOR MP47 HECTORRA 3' => 'MATADOR MP 47 HECTORRA 3',
				'CONTINENTAL CCC VIKING' => 'CONTINENTAL CONTICROSSCONTACT VIKING',
				'MATADOR MP61 ADHESSA EVO' => 'MATADOR MP 61 ADHESSA M+S',
				'CONTINENTAL CROSSCONTACT UHP' => 'CONTINENTAL CONTICROSSCONTACT UHP',
				'NOKIAN HAKKAPELIITTA LT-2' => 'NOKIAN TYRES HAKKAPELIITTA LT2',
				'CONTINENTAL PREMIUM CONTACT-2' => 'CONTINENTAL CONTIPREMIUMCONTACT 2',
				'CONTINENTAL CROSSCONTACT LX 2' => 'CONTINENTAL CONTICROSSCONTACT LX2',
				'КАМА EURO КАМА EURO-236' => 'КАМА-ЕВРО КАМА-ЕВРО-236',
				'CONTINENTAL ECOCONTACT 3' => 'CONTINENTAL CONTIECOCONTACT 3',
				'PIRELLI WINTER 210 SOTTOZERO SERIE II' => 'PIRELLI WINTER SOTTOZERO II',
				'PIRELLI WINTER 240 SOTTOZERO SERIE II' => 'PIRELLI WINTER SOTTOZERO II',
				'CONTINENTAL TS790' => 'CONTINENTAL CONTIWINTERCONTACT TS 790',
				'PIRELLI WINTER SOTTOZERO SERIE III' => 'PIRELLI WINTER SOTTOZERO 3',
				'PIRELLI WINTER ICE ZERO' => 'PIRELLI ICE ZERO',
				'MATADOR MP54 SIBIR SNOW' => 'MATADOR MP 54 SIBIR SNOW M+S',
				'MATADOR MP92 SIBIR SNOW' => 'MATADOR MP 92 SIBIR SNOW',
				'NEXEN ROADIAN HP' => 'NEXEN ROADIAN HP SUV',
				'MAXXIS MASLW' => 'MAXXIS MA-SLW',
				'MATADOR MPS530 SIBIR SNOW VAN' => 'MATADOR MPS 530 SIBIR SNOW VAN',
				'MATADOR MP52 NORDICCA BASIC' => 'MATADOR MP 52 NORDICCA BASIC',
				'MATADOR MP92 SIBIR SNOW' => 'MATADOR MP 92 SIBIR SNOW',
				'CONTINENTAL 4X4WINTERCONTACT' => 'CONTINENTAL CONTI4X4WINTERCONTACT',
				'PIRELLI WINTER 240 SOTTOZERO' => 'PIRELLI WINTER SOTTOZERO',
				'КАМА EURO КАМА EURO-224' => 'КАМА-ЕВРО КАМА-ЕВРО-224',
				'PIRELLI WINTER 270 SOTTOZERO SERIE II' => 'PIRELLI WINTER SOTTOZERO II',	
				'MAXXIS SP3' => 'MAXXIS ARCTIC TREKKER SP03',
				'КАМА КАМА-505 IRBIS' => 'КАМА КАМА-505',
				'CONTINENTAL CROSSCONTACT WINTER' => 'CONTINENTAL CONTICROSSCONTACT WINTER',
				'MAXXIS UE168N' => 'MAXXIS UE168 (N)',
				'MICHELIN ENERGY SAVER+' => 'MICHELIN ENERGY SAVER PLUS',
				'MICHELIN AGILIS+' => 'MICHELIN AGILIS PLUS',
				'NOKIAN ROTIIVA A/T' => 'NOKIAN TYRES ROTIIVA AT',
				'HANKOOK WINTER I*CEPT IZ2 W616' => 'HANKOOK TIRE WINTER I*CEPT IZ 2 W616',
				'HANKOOK VENTUS PRIME 3 K125' => 'HANKOOK TIRE VENTUS PRIME3 K125',
				'CONTINENTAL CROSSCONTACT LX SPORT' => 'CONTINENTAL CONTICROSSCONTACT LX SPORT',
				'CONTINENTAL VIKINGCONTACT 7' => 'CONTINENTAL CONTIVIKINGCONTACT 7',
				'BLACKLION W506 WINTER TAMER' => 'BLACKLION W506 ICE PIONEER',
				'MATADOR MPS330 MAXILLA 2' => 'MATADOR MPS 330 MAXILLA 2',
				'MAXXIS M-8060 TREPADOR' => 'MAXXIS M8060 TREPADOR',
				'NITTO 90W WINTER' => 'NITTO NT90W',
				'CORDIANT OFF ROAD, OS-501' => 'CORDIANT OFF ROAD',
				'NITTO WINTER SN2' => 'NITTO SN 2 WINTER',
				'CONTINENTAL TS810 S' => 'CONTINENTAL CONTIWINTERCONTACT TS 810 SPORT',
				'CONTINENTAL TS800' => 'CONTINENTAL CONTIWINTERCONTACT TS 800',
				'MAXXIS NS-5' => 'MAXXIS PREMITRA ICE NORD NS5',
				'MAXXIS M-8090 CREEPY CRAWLER' => 'MAXXIS M8090 CREEPY CRAWLER',
				'MATADOR MP59 NORDICCA' => 'MATADOR MP 59 NORDICCA M+S',
				'MATADOR MP50 SIBIR ICE' => 'MATADOR MP 50 SIBIR ICE',
				'CONTINENTAL ECOCONTACT 5' => 'CONTINENTAL CONTIECOCONTACT 5',
				'HANKOOK VENTUS PRIME 2 K115' => 'HANKOOK TIRE VENTUS PRIME2 K115',
				'CONTINENTAL CONTISPORTCONTACT-6' => 'CONTINENTAL SPORTCONTACT 6',
				'CORDIANT SPORT 2, PS-501' => 'CORDIANT SPORT 2',
				'CORDIANT COMFORT 2, PS-6' => 'CORDIANT COMFORT 2',
				'CORDIANT ROAD RUNNER, PS-1' => 'CORDIANT ROAD RUNNER',
				'CONTINENTAL 4X4CONTISPORTCONTACT' => 'CONTINENTAL CONTI4X4SPORTCONTACT',
				'CONTINENTAL ECOCONTACT EP' => 'CONTINENTAL CONTIECOCONTACTEP',
				'NEXEN WG-ICE' => 'NEXEN WINGUARD ICE',
				'MAXXIS M36+' => 'MAXXIS M-36+ VICTRA',
				'MAXXIS MT772' => 'MAXXIS RAZR MT MT-772',
				'DUNLOP(EU) SP SPORT MAXX GT' => 'DUNLOP SP SPORT MAXX GT',
				'VIATTI BOSCO A/T V-237' => 'VIATTI BOSCO A/T',
				'MAXXIS M-8080 MUDZILLA' => 'MAXXIS M8080 MUDZILLA',
				'DUNLOP SPORT BLU RESPONSE' => 'DUNLOP SPORT BLURESPONSE',
				'MAXXIS MAW2' => 'MAXXIS MA-W2 WINTERMAXX',
				'SAVA ESKIMOHP2' => 'SAVA ESKIMO HP2',
				'CONTINENTAL TS850 P' => 'CONTINENTAL CONTIWINTERCONTACT TS 850P',
				'CONTINENTAL TS860' => 'CONTINENTAL CONTIWINTERCONTACT TS 860',
				'CORDIANT BUSINESS, CA-1' => 'CORDIANT BUSINESS CA',
				'NEXEN WG-SPORT' => 'NEXEN WINGUARD SPORT',
				'NITTO NT 421Q' => 'NITTO NT421Q',
				'NITTO NT 420S' => 'NITTO NT420S',
				'MICHELIN AGILIS51' => 'MICHELIN AGILIS 51',
				'MAXXIS UE101' => 'MAXXIS UE-101',
				'MICHELIN PILOT SPORT 4S' => 'MICHELIN PILOT SPORT 4 S',
				'HANKOOK VENTUS V12 EVO 2 K120' => 'HANKOOK TIRE VENTUS V12 EVO2 K120',
				'YOKOHAMA V105T' => 'YOKOHAMA ADVAN SPORT V105',
				'NOKIAN ROTIIVA H/T' => 'NOKIAN TYRES ROTIIVA HT',
				'CORDIANT ALL TERRAIN, OA-1' => 'CORDIANT ALL TERRAIN',
				'MAXXIS MASTL' => 'MAXXIS MA-STL',
				'NEXEN NPRIZ 4S' => 'NEXEN N\'PRIZ 4S',
				'HANKOOK WINTER I*CEPT EVO2 W320' => 'HANKOOK TIRE WINTER I*CEPT EVO 2 W320',
				'CONTINENTAL VANCO FOURSEASON-2' => 'CONTINENTAL VANCOFOURSEASON 2',
				'TOYO OPAT+' => 'TOYO OPEN COUNTRY A/T PLUS',
				'HANKOOK WINTER I*CEPT W605' => 'HANKOOK TIRE I CEPT W605',
				'CONTINENTAL PREMIUM CONTACT' => 'CONTINENTAL CONTIPREMIUMCONTACT',
				'GENERAL TIRE GRABBER HTS60' => 'GENERAL TIRE GRABBER HTS 60',
				'NEXEN WG-SNOW G WH2' => 'NEXEN WINGUARD SNOW G WH2',
				'KUMHO 7400' => 'KUMHO KW7400',
				'CORDIANT SPORT 3, PS-2' => 'CORDIANT SPORT 3',
				'TOYO OBG3S' => 'TOYO OBSERVE G3-ICE',
				'FIRESTONE DESTINATION LE-02' => 'FIRESTONE DESTINATION LE2',
				'PIRELLI WINTER 210 SNOWCONTROL SERIE III' => 'PIRELLI WINTER SNOWCONTROL SERIE 3',
				'CONTINENTAL CROSSCONTACT LX' => 'CONTINENTAL CONTICROSSCONTACT LX',
				'NEXEN NFERA SU1' => 'NEXEN N\'FERA SU1',
				'BLACKLION BU66 CHAMPOINT' => 'BLACKLION BU66',
				'КАМА EURO КАМА EURO-518' => 'КАМА-ЕВРО КАМА-ЕВРО-518',
				'HANKOOK VENTUS V12 EVO 2 K120' => 'HANKOOK TIRE VENTUS V12 EVO2 K120',
				'HANKOOK DYNAPRO AT-M RF10' => 'HANKOOK TIRE DYNAPRO ATM RF10',
				'TUNGA ZODIAK 2 PS-7' => 'TUNGA ZODIAK 2',
				'PIRELLI WINTER 210 SOTTOZERO' => 'PIRELLI WINTER SOTTOZERO',
				'NEXEN CP671' => 'NEXEN CLASSE PREMIERE 671',
				'BLACKLION BW56 WINTER TAMER' => 'BLACKLION BW56',
				'NEXEN CP643A' => 'NEXEN CLASSE PREMIERE 643A',
				'NEXEN WG-ICE PLUS' => 'NEXEN WINGUARD ICE PLUS',
				'MAXXIS NS-5' => 'MAXXIS PREMITRA ICE NORD NS5',
				'MAXXIS ME-3+' => 'MAXXIS MECOTRA ME3',
				'NEXEN NPRIZ RH1' => 'NEXEN N\'PRIZ RH1',
				'YOKOHAMA AE50' => 'YOKOHAMA BLUEARTH-A AE-50',
				'NEXEN NFERA RU1' => 'NEXEN N FERA RU1',
				'GISLAVED NORD FROST NF200' => 'GISLAVED NORD FROST 200',
				'MATADOR MP30 SIBIR ICE 2' => 'MATADOR MP 30 SIBIR ICE 2',
				'CONTINENTAL ECOCONTACT 6' => 'CONTINENTAL CONTIECOCONTACT 6',
				'MATADOR MPS500 SIBIR ICE VAN' => 'MATADOR MPS 500 SIBIR ICE VAN',
				'SAVA ESKIMOICEI' => 'SAVA ESKIMO ICE'
			]
		];

		$this->configs[71567] = 
		[
			'model_replace' =>
			[
				'iceGuard' 	=> 'ice Guard',
				'Studless' 	=> '',
				'Stud'		=> '',
			],
			'brand_model_replace_all' =>
			[
				'NOKIAN WR D4' => 'NOKIAN TYRES WR D4',
				'NOKIAN WR C3' => 'NOKIAN TYRES WR C3',
				'BFGOODRICH ALL TERRAIN T/A KO2' => 'BFGOODRICH ALL-TERRAIN T/A KO2',
				'TOYO OBSERVE ICE FREEZER' => 'TOYO OBSERVE ICE-FREEZER',
				'TRIANGLE TR777' => 'TRIANGLE GROUP TR777',
				'TRIANGLE TR797' => 'TRIANGLE GROUP TR797',
				'TRIANGLE PS01' => 'TRIANGLE GROUP PS01',
				'TRIANGLE TR257' => 'TRIANGLE GROUP TR257',
				'NOKIAN HAKKAPELIITTA R3' => 'NOKIAN TYRES HAKKAPELIITTA R3',
				'NOKIAN HAKKAPELIITTA R3 SUV' => 'NOKIAN TYRES HAKKAPELIITTA R3 SUV',
				'NORDMAN NORDMAN RS2' => 'NOKIAN TYRES NORDMAN RS2',
				'NOKIAN HAKKAPELIITTA 7' => 'NOKIAN TYRES HAKKAPELIITTA 7',
				'NOKIAN HAKKAPELIITTA 8 SUV' => 'NOKIAN TYRES HAKKAPELIITTA 8 SUV',
				'FORMULA FORMULA ICE' => 'FORMULA ICE',
				'NOKIAN HAKKAPELIITTA R2' => 'NOKIAN TYRES HAKKAPELIITTA R2',
				'NOKIAN HAKKAPELIITTA R2 SUV' => 'NOKIAN TYRES HAKKAPELIITTA R2 SUV',
				'NORDMAN NORDMAN 7 SUV' => 'NOKIAN TYRES NORDMAN 7 SUV',
				'NOKIAN HAKKAPELIITTA CR3' => 'NOKIAN TYRES HAKKAPELIITTA CR3',
				'NORDMAN NORDMAN 5' => 'NOKIAN TYRES NORDMAN 5',
				'NORDMAN NORDMAN C' => 'NOKIAN TYRES NORDMAN C',
				'NORDMAN NORDMAN 7' => 'NOKIAN TYRES NORDMAN 7',
				'NORDMAN NORDMAN RS2 SUV' => 'NOKIAN TYRES NORDMAN RS2 SUV',
				'NOKIAN WR SUV 3' => 'NOKIAN TYRES WR SUV 3',
				'NOKIAN WR A3' => 'NOKIAN TYRES WR A3',
				'NOKIAN HAKKAPELIITTA 9' => 'NOKIAN TYRES HAKKAPELIITTA 9',
				'NOKIAN HAKKAPELIITTA C3' => 'NOKIAN TYRES HAKKAPELIITTA C3',
				'PIRELLI SCORPION VERDE ALL-SEASON' => 'PIRELLI SCORPION VERDE ALL SEASON',
				'NOKIAN HAKKAPELIITTA 8' => 'NOKIAN TYRES HAKKAPELIITTA 8',
				'MICHELIN LATITUDE X-ICE NORTH 2+' => 'MICHELIN LATITUDE X-ICE NORTH 2 +',
				'NOKIAN WR A4' => 'NOKIAN TYRES WR A4',
				'PIRELLI CINTURATO WINTER' => 'PIRELLI WINTER CINTURATO',
				'BFGOODRICH MUD TERRAIN T/A KM2' => 'BFGOODRICH MUD-TERRAIN T/A KM2',
				'HANKOOK WINTER RW06' => 'HANKOOK TIRE WINTER RW06',
				'HANKOOK WINTER I*PIKE RS2 W429' => 'HANKOOK TIRE WINTER I*PIKE RS2 W429',
				'HANKOOK I*PIKE RW11' => 'HANKOOK TIRE I*PIKE RW11',
				'GISLAVED NORD*FROST VAN' => 'GISLAVED NORD FROST VAN',
				'GISLAVED SOFT*FROST 200' => 'GISLAVED SOFT FROST 200',
				'GISLAVED NORD*FROST 200' => 'GISLAVED NORD FROST 200',
				'HANKOOK WINTER I*PIKE LT RW09' => 'HANKOOK TIRE WINTER I*PIKE LT RW09',
				'HANKOOK WINTER I*CEPT EVO W310' => 'HANKOOK TIRE WINTER I*CEPT EVO W310',
				'HANKOOK DYNAPRO I*CEPT RW08' => 'HANKOOK TIRE DYNAPRO I*CEPT RW08',
				'MATADOR MP 92 SIBIR SNOW SUV' => 'MATADOR MP 92 SIBIR SNOW SUV M+S',
				'TRIANGLE PL01' => 'TRIANGLE GROUP SNOW PL01',
				'MATADOR MP 54 SIBIR SNOW' => 'MATADOR MP 54 SIBIR SNOW M+S',
				'MARSHAL I\'ZEN RV KC16' => 'MARSHAL I\'ZEN RV STUD KC16',
				'BRIDGESTONE DUELER A/T 697' => 'BRIDGESTONE DUELER A/T D697',
				'HANKOOK WINTER I*CEPT W605' => 'HANKOOK TIRE I CEPT W605',
				'PIRELLI WINTER SOTTOZERO SERIE III' => 'PIRELLI WINTER SOTTOZERO 3',
				'MICHELIN X-ICE XI3' => 'MICHELIN X-ICE 3',
				'PIRELLI WINTER SOTTOZERO SERIE II' => 'PIRELLI WINTER SOTTOZERO II',
				'YOKOHAMA ICE GUARD G075' => 'YOKOHAMA ICEGUARD SUV G075',
				'YOKOHAMA SUPER VAN Y354' => 'YOKOHAMA Y354',
				'DUNLOP JP GRANDTREK SJ6' => 'DUNLOP GRANDTREK SJ6',
				'TIGAR CARGO SPEED WINTER' => 'TIGAR CARGOSPEED WINTER',
				'MICHELIN LATITUDE ALPIN 2' => 'MICHELIN LATITUDE ALPIN LA2',
				'VIATTI BOSCO A/T V-237' => 'VIATTI BOSCO A/T',
				'NOKIAN HAKKAPELIITTA LT 2' => 'NOKIAN TYRES HAKKAPELIITTA LT2',
				'MICHELIN PILOT ALPIN PA4' => 'MICHELIN PILOT ALPIN 4',
				'CONTINENTAL CONTIWINTERCONTACT TS 850 P SUV' => 'CONTINENTAL CONTIWINTERCONTACT TS 850P SUV',
				'CONTINENTAL VIKINGCONTACT 7' => 'CONTINENTAL CONTIVIKINGCONTACT 7'				
			]
		];

		$this->configs[56091] = 
		[
			'model_replace' =>
			[
				'HKPL' => 'Hakkapeliitta',
				'IC-7' => 'Ice Cruiser 7',
				'IG-35' => 'IG35',
				'CARGO SPEED' => 'CARGOSPEED',
				'С' => 'C',
				'OBGSi5' => 'Observe GSi-5',
				'PXT1R' => 'Proxes T1-R',
				'KW-31' => 'KW31',
			]
		];

		$this->configs[52115] = 
		[
			'model_replace' =>
			[
				'HKPL' => 'Hakkapeliitta',
				'IC-7' => 'Ice Cruiser 7',
				'IG-35' => 'IG35',
				'CARGO SPEED' => 'CARGOSPEED',
				'С' => 'C',
				'OBGSi5' => 'Observe GSi-5',
				'PXT1R' => 'Proxes T1-R',
			]
		];

		$this->configs[104439] = 
		[
			'brand_model_replace' =>
			[
				'ICIGUARD' => 'ice Guard',
				'HKPL' => 'Hakkapeliitta',
				'MP47 Hectorra 3' => 'MP 47 Hectorra 3',
			]
		];

		$this->configs[105086] = 
		[
			'model_replace' =>
			[
				'iceGuard' => 'ice Guard',
				'Studless' => '',
				'Stud' => '',
			]
		];

		$this->configs[104438] = 
		[
			'model_replace' =>
			[
				'ICIGUARD' => 'ice Guard',
				' STUDLESS ' => ' ',
				' STUD ' => ' ',
				'ICE CONTACT' => 'iceContact',
				'MP47 Hectorra 3' => 'MP 47 Hectorra 3',
			]
		];

		$this->configs[103478] = 
		[
			'model_replace' =>
			[
				'ICIGUARD' => 'ice Guard',
				' STUDLESS ' => ' ',
				' STUD ' => ' ',
				'ICE CONTACT' => 'iceContact',
				'MP47 Hectorra 3' => 'MP 47 Hectorra 3',
			]
		];	

		$this->configs[335208] = 
		[
			'brand_replace' =>
			[
				'NZ' => 'NZ Wheels',
				'Replica RPLC' => 'RPLC-Wheels',
				'LS' => 'LS Wheels',
				'NEO' => 'Neo Wheels',
				'СКАД' => 'SKAD',
				'Скад' => 'SKAD',
				'k&k' => 'K&K',
				'kik' => 'K&K',
				'KIK' => 'K&K',
				'КиК' => 'K&K',
				'КИК' => 'K&K',
				'Кик' => 'K&K',
				'к&к' => 'K&K',
				'кик' => 'K&K',
				'К&К' => 'K&K',		
			],
			'model_replace' =>
			[
				'LS NG236' => 'NG236',
				'LS BY503' => 'BY503',
				'LS NG238' => 'NG238',
				'LS NG241' => 'NG241',
				'Grip' => 'Grip (Transporter)',
				'103 dark' => '103',
				'(9265)' => '9265',
				'Daimond' => 'Diamond',
				'C.T.G' => 'C.T.G.',
				'R1- Рольф' => 'R1-Рольф',
				'Note' => 'КС427 (15_Note)',
			]
		];

		$this->configs[329069] = 
		[
			'brand_replace' =>
			[
				'NZ' => 'NZ Wheels',
				'Neo' => 'Neo Wheels',
				'Tech Line' => 'Tech-Line',
				'LS' => 'LS Wheels',
				'СКАД' => 'SKAD',
				'Скад' => 'SKAD',
				'k&k' => 'K&K',
				'kik' => 'K&K',
				'KIK' => 'K&K',
				'КиК' => 'K&K',
				'КИК' => 'K&K',
				'Кик' => 'K&K',
				'к&к' => 'K&K',
				'кик' => 'K&K',
				'К&К' => 'K&K',		
			],
			'model_replace' =>
			[
				'114' =>'LS114',
			]
		];

		$this->configs[367949] = 
		[
			'brand_replace' =>
			[
				'NZ' => 'NZ Wheels',
				'Neo' => 'Neo Wheels',
				'Tech Line' => 'Tech-Line',
				'LS' => 'LS Wheels',
				'СКАД' => 'SKAD',
				'Скад' => 'SKAD',
				'k&k' => 'K&K',
				'kik' => 'K&K',
				'KIK' => 'K&K',
				'КиК' => 'K&K',
				'КИК' => 'K&K',
				'Кик' => 'K&K',
				'к&к' => 'K&K',
				'кик' => 'K&K',
				'К&К' => 'K&K',		
			],
			'model_replace' =>
			[
				'114' =>'LS114',
			]
		];

		$this->configs[361182] = 
		[
			'brand_model_replace' =>
			[
				'Tech Line' => 'Tech-Line',
				'Lege Artis' => 'LegeArtis',
				'СКАД' => 'SKAD',
				'Скад' => 'SKAD',
				'k&k' => 'K&K',
				'kik' => 'K&K',
				'KIK' => 'K&K',
				'КиК' => 'K&K',
				'КИК' => 'K&K',
				'Кик' => 'K&K',
				'к&к' => 'K&K',
				'кик' => 'K&K',
				'К&К' => 'K&K',		
				'КС749 (Sportage)' => 'КС749',
				'Офф-лайн (КС516)' => 'Офф-лайн',
				'КС623' => 'КС623 (17_Juke)',
			]
		];

		$this->configs[369582] = 
		[
			'brand_replace' =>
			[
				'NZ' => 'NZ Wheels',
				'Neo' => 'Neo Wheels',
				'Tech Line' => 'Tech-Line',
				'LS' => 'LS Wheels',
				'СКАД' => 'SKAD',
				'Скад' => 'SKAD',
				'k&k' => 'K&K',
				'kik' => 'K&K',
				'KIK' => 'K&K',
				'КиК' => 'K&K',
				'КИК' => 'K&K',
				'Кик' => 'K&K',
				'к&к' => 'K&K',
				'кик' => 'K&K',
				'К&К' => 'K&K',
				'RPLC' => 'RPLC-Wheels',
			],
			'model_replace' =>
			[
				'114' => 'LS114',
				'TD graphite' => 'TD',
				'TH dark' => 'TH',
				'TX graphite' => 'TX',
			]
		];

		$this->configs[350554] = 
		[
			'brand_replace' =>
			[
				'NZ' => 'NZ Wheels',
				'Neo' => 'Neo Wheels',
				'Tech Line' => 'Tech-Line',
				'LS' => 'LS Wheels',
				'СКАД' => 'SKAD',
				'Скад' => 'SKAD',
				'k&k' => 'K&K',
				'kik' => 'K&K',
				'KIK' => 'K&K',
				'КиК' => 'K&K',
				'КИК' => 'K&K',
				'Кик' => 'K&K',
				'к&к' => 'K&K',
				'кик' => 'K&K',
				'К&К' => 'K&K',	
			],
			'model_replace' =>
			[
				'384-3101012-01' => '384-3101012-01 Alive', 
			]
		];				
	}

	public function getConfig($array)
	{
		$config = $this->configs[$array['import_id']] ?? [];

		return array_merge($array, $config);
	}
}